package com.mprs.transaction.domain;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * JPA entity representing a merchant payment transaction.
 * Maps to the 'transactions' table created by Flyway migration V1.
 *
 * Immutable business key: transaction_id (assigned by upstream system).
 * Surrogate key: id (auto-generated by DB).
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "transactions")
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Business identifier — unique across the system.
     * Assigned by the upstream payment processor (e.g. "T1001").
     * Never auto-generated by MPRS.
     */
    @Column(name = "transaction_id", nullable = false, unique = true, length = 100)
    private String transactionId;

    /**
     * Transaction amount in USD.
     * NUMERIC(19,4) in DB — supports large amounts with sub-cent precision.
     */
    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal amount;

    /**
     * Current status of the transaction.
     * Stored as a string in DB for readability and forward compatibility.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 50)
    private TransactionStatus status;

    /**
     * Date the transaction was settled.
     * Used as the primary filter for reconciliation windows.
     */
    @Column(name = "settlement_date", nullable = false)
    private LocalDate settlementDate;

    /**
     * Identifier of the merchant who owns this transaction.
     */
    @Column(name = "merchant_id", nullable = false, length = 100)
    private String merchantId;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    // ── Convenience constructor for service layer ─────────────────

    public Transaction(String transactionId, BigDecimal amount,
                       TransactionStatus status, LocalDate settlementDate,
                       String merchantId) {
        this.transactionId  = transactionId;
        this.amount         = amount;
        this.status         = status;
        this.settlementDate = settlementDate;
        this.merchantId     = merchantId;
    }

    /**
     * Business rule: only SETTLED transactions are eligible for payout.
     */
    public boolean isEligibleForPayout() {
        return TransactionStatus.SETTLED.equals(this.status);
    }
}